### ISSUE TITLE
Clear documentation should be added

### ISSUE THREAD

**Issue by uzbekman2005** [golanguzb70/middleware#1]
It would be create a documentation for each middleware is written in their readme.md files and link to their docs in main readme.md file

**Comment by golanguzb70** [comment]
Hi there! 👋

Thank you for opening an issue in our open source project. We appreciate your contribution and are here to assist you. Please provide any necessary details or additional information related to the issue, and we'll do our best to address it promptly.

Happy coding! 🚀

**Comment by golanguzb70** [comment]
Yes documentation will be added.
